image: node:latest

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: build
  script: yarn run deploy 